apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTlONkZnL2ZzQ2hCZzR5VlJ3OXVpeWlYYVhzUHBRVXFGbE1TcXFPRnUvTWtFCkRxeTVKczFNclpFeWdRLzg3NEk3LzRZM1lncWFFZnBISFk1T2dCb1kvZ1d5SEVvRnczRU9vMnJoR0NKYTkxQlEKZllEMFg0RHFSL1d6R1lCbFgrZ2FOUlpTR3BOZDQzMVRydWdkRHJVdmZnWmJWcDc4VGY1b3JzcXdYbTVCbTNhUApsZmhwbEdwaWxPeXRCY2tUajEwMXFrdTgzOTRyV1dJallaM1JaVzJFR1ZwbGRSaE1MY1kxUGgyRDdQQjhKVG9hCmwrVHFNYTdmNnpjWjZkSEpZdldYcjVTWGdIYi9zcUFMR09xRWhyS25kcWF2dXoydkk4RkpvdG0rYkwxVGx2b3kKSWtpWS9qbkl4OTlia3VxaG1LbzNhc2JNN0ZXcGpVcE9zbTEvZjZMRElRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBTEhrWWlaSEpKOXhsV05ZcU1Hc2VwVEo1ZmhIcFpTeW1oVk8rUmt4OU5leVRzVTByZUNXCmNCZzEwd1FwWjZINHhoMFRJYm5Lb2RzRXBnQUtDVXpiVFlKTDM3ZCtGK1p3YjVqRDBidlpPVHFzZE9YUXNuNUIKZHNIMkNub2l5dmtnQjdoSDdVbVhML1RZSmZTYTFqWjZqcS94dmdoc1ZaTnFXZm8yUFBaMTFyQ3JJLzR0ZktiQwpVVjdBKy9nU29CRlEyUmdxT0RYckkzdDlVOFp6Uld2ZkdoanJCVVROc2p1WVRlcWQ4WTlSTXBhTk05MHViK1NtClpJaXpDekNxMGh4V3lOKzlLdlNzcVpSVG1DWU56SGZIb1JEcFdXUHhtazh2elRJRFpXc29PT2YwVkUwa1hkbE4KN1cwNERzV001UkZSRjZleHVOUGIvaHFXMHpyS3FVd0dYcE09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth