apiVersion: extensions/v1beta1
kind: ingress
metadata:
  name: ingress-wear
spec: #multiple path with multiple backend with multiple path and multiple host
  rules:
    - host: wear.my-online.com
      http:
        paths:
          - path: /wear
            backend:
              serviceName: wear-service
              servicePort: 80
          - path: /wear2
            backend:
              serviceName: wear2-service
              servicePort: 81  
    - host: watch.my-online.com
      http:
        paths:            
          - path: /watch
            backend:
              serviceName: watch-service
              servicePort: 80    