apiVersion: extensions/v1beta1
kind: ingress
metadata:
  name: ingress-wear
spec: #multiple path with multiple backend with one path and one host
  rules:
    - http:
        paths:
          - path: /wear
            backend:
              serviceName: wear-service
              servicePort: 80
          - path: /watch
            backend:
              serviceName: watch-service
              servicePort: 80    