apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt 
    #certificate-authority-data: base64 of ca.crt
    server: https://172.17.0.31:6443
  name: kubernetes
contexts:
- name: kubernetes-admin@kubernetes
  context:
    cluster: kubernetes
    user: kubernetes-admin
    namespace: finance
current-context: kubernetes-admin@kubernetes
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate: clent.crt #certificate-authority-data:
    client-key: client.key #client-key-data   