apiVersion: networking.k8s.io/v1
kind: NetwokingPolicy
metadata:
  name: db-policy
spec:
  podSelector:
    matchLabels:
      role: db-policy
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            name: api-pod
      ports:
        - protocol: TCP
          port: 3306
