apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    app: myapp
spec:
  containers:
  - name: red
    image: busybox:1.28
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'git clone <some-repository-that-will-be-used-by-application> ; done;']
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
  - name: init-mydb
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']


