apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    name: webapp-pod
spec:
  containers:
  - name: webapp-color
    image: kodekloud/simple-webapp-mysql
    envFrom:
      - secretRef:
          name: db-secret
    # volume:
    #   - name: app-secret-volume
    #     secret:
    #       secretName: app-secret
    # env:
    #   - name: test
    #     value: test_value
    #   - name: db_password
    #     valueFrom:
    #       secretKeyRef:
    #         name: app-secret
    #         key: DB_PASSWORD