apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  labels:
    app: myapp
    type: front-end
spec:
  securityContext:
    runAsUser: 1000
    capabilities:
      add: ["MAC_ADMIN"]
  containers:
  - name: nginx
    image: private-registry.io/apps/internal-app
    securityContext:
      runAsUser: 1000
      capabilities:
        add: ["MAC_ADMIN"]
  imagePullSecrets:
  - name: NAME #kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string]