apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: delayed-volume-sc
provisioner:  kubernetes.io/no-provisioner #kubernetes.io/gce-p
volumeBindingMode: WaitForFirstConsumer
# parameters:
#   type: pd-standards
#   replication-type: none